2019-03-18 11:37:20,229 ERROR 3580 nodejs.ClusterClientNoResponseError: client no response in 67843ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Desktop\API\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 3580
hostname: 20161212-102137

2019-03-18 13:54:39,667 ERROR 3580 nodejs.ClusterClientNoResponseError: client no response in 6102005ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Desktop\API\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 3580
hostname: 20161212-102137

2019-03-18 14:40:29,734 ERROR 3240 [-/127.0.0.1/-/23ms POST /backend/v1/login] nodejs.SequelizeDatabaseError: Unknown column 'like_ids' in 'field list'
    at Query.formatError (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.execute (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\connection.js:72:12)
    at PacketParser.executeStart (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\dialects\mysql\query.js:57:12)
    at Promise.try.then.connection (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\sequelize.js:555:8)
    at C:\Users\Administrator\Desktop\API\node_modules\retry-as-promised\index.js:39:21
    at retryAsPromised (C:\Users\Administrator\Desktop\API\node_modules\retry-as-promised\index.js:29:10)
    at Sequelize.query (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\sequelize.js:454:28)
    at QueryInterface.select (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\query-interface.js:1104:27)
    at Promise.try.then.then.then (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\model.js:1598:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Function.findAll (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\model.js:1595:8)
    at Function.findOne (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\model.js:1752:17)
    at UserService.login (C:\Users\Administrator\Desktop\API\app\service\user.js:84:38)
    at UserController.login (C:\Users\Administrator\Desktop\API\app\controller\backend\user.js:20:44)
    at Object.callFn (C:\Users\Administrator\Desktop\API\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\API\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\router.js:195:33)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at C:\Users\Administrator\Desktop\API\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:56
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at i18n (C:\Users\Administrator\Desktop\API\node_modules\egg-i18n\app\middleware\i18n.js:13:12)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at dta (C:\Users\Administrator\Desktop\API\node_modules\egg-security\lib\middlewares\dta.js:12:12)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at xframe (C:\Users\Administrator\Desktop\API\node_modules\egg-security\lib\middlewares\xframe.js:7:11)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at xssProtection (C:\Users\Administrator\Desktop\API\node_modules\egg-security\lib\middlewares\xssProtection.js:7:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'like_ids' in 'field list'","sql":"SELECT `username`, `password`, `avatar`, `id`, `created_at`, `updated_at`, `nickname`, `like_count`, `mood`, `like_ids`, `role` FROM `users` AS `user` WHERE `user`.`username` = 'aptx4869' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'like_ids' in 'field list'","sql":"SELECT `username`, `password`, `avatar`, `id`, `created_at`, `updated_at`, `nickname`, `like_count`, `mood`, `like_ids`, `role` FROM `users` AS `user` WHERE `user`.`username` = 'aptx4869' LIMIT 1;"}
sql: "SELECT `username`, `password`, `avatar`, `id`, `created_at`, `updated_at`, `nickname`, `like_count`, `mood`, `like_ids`, `role` FROM `users` AS `user` WHERE `user`.`username` = 'aptx4869' LIMIT 1;"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 3240
hostname: 20161212-102137

2019-03-18 14:41:09,067 ERROR 3240 [-/127.0.0.1/-/270ms POST /backend/v1/login] nodejs.SequelizeDatabaseError: Unknown column 'like_ids' in 'field list'
    at Query.formatError (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\dialects\mysql\query.js:247:16)
    at Query.handler [as onResult] (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\dialects\mysql\query.js:68:23)
    at Query.execute (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\commands\command.js:30:14)
    at Connection.handlePacket (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\connection.js:449:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\connection.js:72:12)
    at PacketParser.executeStart (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (C:\Users\Administrator\Desktop\API\node_modules\mysql2\lib\connection.js:79:25)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
From previous event:
    at Query.run (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\dialects\mysql\query.js:57:12)
    at Promise.try.then.connection (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\sequelize.js:558:20)
From previous event:
    at Promise.resolve.retryParameters (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\sequelize.js:555:8)
    at C:\Users\Administrator\Desktop\API\node_modules\retry-as-promised\index.js:39:21
    at retryAsPromised (C:\Users\Administrator\Desktop\API\node_modules\retry-as-promised\index.js:29:10)
    at Sequelize.query (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\sequelize.js:454:28)
    at QueryInterface.select (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\query-interface.js:1104:27)
    at Promise.try.then.then.then (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\model.js:1598:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Function.findAll (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\model.js:1595:8)
    at Function.findOne (C:\Users\Administrator\Desktop\API\node_modules\sequelize\lib\model.js:1752:17)
    at UserService.login (C:\Users\Administrator\Desktop\API\app\service\user.js:84:38)
    at UserController.login (C:\Users\Administrator\Desktop\API\app\controller\backend\user.js:20:44)
    at Object.callFn (C:\Users\Administrator\Desktop\API\node_modules\egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\API\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\@eggjs\router\lib\router.js:195:33)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at C:\Users\Administrator\Desktop\API\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:56
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at i18n (C:\Users\Administrator\Desktop\API\node_modules\egg-i18n\app\middleware\i18n.js:13:12)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at dta (C:\Users\Administrator\Desktop\API\node_modules\egg-security\lib\middlewares\dta.js:12:12)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at xframe (C:\Users\Administrator\Desktop\API\node_modules\egg-security\lib\middlewares\xframe.js:7:11)
    at dispatch (C:\Users\Administrator\Desktop\API\node_modules\koa-compose\index.js:42:32)
    at xssProtection (C:\Users\Administrator\Desktop\API\node_modules\egg-security\lib\middlewares\xssProtection.js:7:11)
name: "SequelizeDatabaseError"
parent: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'like_ids' in 'field list'","sql":"SELECT `username`, `password`, `avatar`, `id`, `created_at`, `updated_at`, `nickname`, `like_count`, `mood`, `like_ids`, `role` FROM `users` AS `user` WHERE `user`.`username` = 'aptx4869' LIMIT 1;"}
original: {"code":"ER_BAD_FIELD_ERROR","errno":1054,"sqlState":"42S22","sqlMessage":"Unknown column 'like_ids' in 'field list'","sql":"SELECT `username`, `password`, `avatar`, `id`, `created_at`, `updated_at`, `nickname`, `like_count`, `mood`, `like_ids`, `role` FROM `users` AS `user` WHERE `user`.`username` = 'aptx4869' LIMIT 1;"}
sql: "SELECT `username`, `password`, `avatar`, `id`, `created_at`, `updated_at`, `nickname`, `like_count`, `mood`, `like_ids`, `role` FROM `users` AS `user` WHERE `user`.`username` = 'aptx4869' LIMIT 1;"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 3240
hostname: 20161212-102137

2019-03-18 15:39:50,707 ERROR 9460 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 9460
hostname: 20161212-102137

2019-03-18 15:39:55,007 ERROR 9460 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 9460
hostname: 20161212-102137

2019-03-19 09:14:40,530 ERROR 11800 nodejs.ClusterClientNoResponseError: client no response in 54282383ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\Administrator\Desktop\API\node_modules\cluster-client\lib\leader.js:77:23)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
name: "ClusterClientNoResponseError"
pid: 11800
hostname: 20161212-102137

